In [1]:
import numpy as np
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import StandardScaler

In [2]:
def Henon(n):
    a = 1.4
    b = 0.3
    x = np.zeros((n+1))
    y = np.zeros((n+1))
    for i in range(n):
        x[i+1] = 1-a*x[i]*x[i] + y[i]
        y[i+1] = b*x[i]
    return (x,y)

    

In [3]:
def Ventanas(x,size):
    size += 1
    arr = np.empty((0,size))
    for i in range(len(x) - size):
        arr = np.vstack((arr,x[i:i + size]))
    return (arr[:,:-1],arr[:,-1])

    

In [4]:
Ventanas(Henon(10)[0],2)

(array([[ 0.        ,  1.        ],
        [ 1.        , -0.4       ],
        [-0.4       ,  1.076     ],
        [ 1.076     , -0.7408864 ],
        [-0.7408864 ,  0.55432228],
        [ 0.55432228,  0.34755162],
        [ 0.34755162,  0.99718771],
        [ 0.99718771, -0.28787117]]),
 array([-0.4       ,  1.076     , -0.7408864 ,  0.55432228,  0.34755162,
         0.99718771, -0.28787117,  1.18313858]))

In [5]:
Xinicial,_ = Henon(100)
X,y = Ventanas(Xinicial,25)

Estandarizamos los datos.

In [6]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = (y - np.mean(y))/np.std(y)


In [7]:
kf = KFold(n_splits=10,shuffle=True)
resultados_train = []
resultados_test = []
model = []
res_train = np.empty((30,0))
res_test = np.empty((30,0))
test_indices = []
etiquetas = []
dicc = [{'kernel': 'rbf','tol': 0.1,'gamma':'auto'}]

for i in range(len(dicc)):
    test_indices2 = []
    for j in range(3):
        for train_index, test_index in kf.split(X):
    #         train_test_split del conjunto train y pillar 1/9 para validación
            X_train, X_test,y_train, y_test = X[train_index],X[test_index],y[train_index],y[test_index]
            
            test_indices2.append(test_index)
    #         print('X_train: {}\n, X_valid: {}\n, X_test: {}'.format(X_train, X_valid, X_test))
            alg = SVR(**dicc[i])
            alg.fit(X_train, y_train)
            model.append(alg)
            y_pred_test = alg.predict(X_test)
            y_pred_train = alg.predict(X_train)
            resultados_train.append(mean_squared_error(y_train,y_pred_train))
            resultados_test.append(mean_squared_error(y_test,y_pred_test))
    
    res_train = np.hstack((res_train, np.array(resultados_train,ndmin=2).T))
    res_test = np.hstack((res_test, np.array(resultados_test,ndmin=2).T))
    resultados_train = []
    resultados_test = []
    test_indices.append(test_indices2)

    
            

In [10]:
res_test

array([[0.70164669],
       [0.67695508],
       [0.45672216],
       [0.50206599],
       [0.98037887],
       [0.62439476],
       [0.42390006],
       [1.1162334 ],
       [1.38668978],
       [0.80517382],
       [0.57991978],
       [0.87553679],
       [0.68189836],
       [0.34411046],
       [0.14816608],
       [1.13693937],
       [0.77595326],
       [1.09771597],
       [0.36154011],
       [1.21837756],
       [0.58381108],
       [0.6685601 ],
       [0.79790681],
       [0.47086448],
       [0.57606575],
       [0.86000137],
       [0.83593131],
       [0.27558717],
       [2.14672089],
       [0.53781339]])